name: test ci
on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
jobs:
  first-job:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version